'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=(...p)=>fs.readFileSync(path.join(root,...p),'utf8');
const pkg=JSON.parse(read('package.json'));
const cfg=read('deployment-config.js'),factory=read('deployment.js'),html=read('index.html');
const standard=JSON.parse(read('deploy','azure','azuredeploy.json'));
const priv=JSON.parse(read('deploy','azure','azuredeploy-private.json'));
const privateDocs=read('deploy','azure','PRIVATE_ONE_CLICK.md'),canonical=read('CANONICAL_PUBLIC_EVE.md'),setter=read('scripts','set-canonical-repository.js'),pages=read('.github','workflows','publish-beta.yml');
assert.equal(pkg.version,'63.0.0');
for(const token of ['azureStandardDeploy','azurePrivateDeploy','Standard Azure','Private Azure','Private network']) assert(html.includes(token),`missing launcher Azure profile UI: ${token}`);
assert(cfg.includes('azurePrivateTemplatePath'));assert(/cfg\.azurePrivateTemplatePath\s*\|\|\s*['\"]deploy\/azure\/azuredeploy-private\.json['\"]/.test(factory));
assert.equal(standard.parameters.containerImage.defaultValue,'ghcr.io/OWNER/REPOSITORY:beta');
const standardApp=standard.resources.find(r=>r.type==='Microsoft.App/containerApps');
assert(standardApp.properties.template.containers[0].env.some(x=>x.name==='EVE_AZURE_NETWORK_PROFILE'&&x.value==='standard'));
assert.equal(priv.contentVersion,'1.2.0.0');
assert.equal(priv.parameters.containerImage.defaultValue,'ghcr.io/OWNER/REPOSITORY:beta');
const types=priv.resources.map(r=>r.type);
for(const type of ['Microsoft.Network/virtualNetworks','Microsoft.Network/privateDnsZones','Microsoft.Network/privateEndpoints','Microsoft.Network/privateEndpoints/privateDnsZoneGroups','Microsoft.App/managedEnvironments','Microsoft.DBforPostgreSQL/flexibleServers','Microsoft.Storage/storageAccounts']) assert(types.includes(type),`private Azure missing ${type}`);
assert(!types.includes('Microsoft.DBforPostgreSQL/flexibleServers/firewallRules'));
const env=priv.resources.find(r=>r.type==='Microsoft.App/managedEnvironments');
assert.equal(env.properties.vnetConfiguration.internal,true);assert.equal(env.properties.publicNetworkAccess,'Disabled');
const storage=priv.resources.find(r=>r.type==='Microsoft.Storage/storageAccounts');
assert.equal(storage.properties.publicNetworkAccess,'Disabled');assert.equal(storage.properties.networkAcls.defaultAction,'Deny');
const pg=priv.resources.find(r=>r.type==='Microsoft.DBforPostgreSQL/flexibleServers');
assert.equal(pg.properties.network.publicNetworkAccess,'Disabled');assert(pg.properties.network.delegatedSubnetResourceId);assert(pg.properties.network.privateDnsZoneArmResourceId);
const app=priv.resources.find(r=>r.type==='Microsoft.App/containerApps');
const appEnv=Object.fromEntries(app.properties.template.containers[0].env.map(x=>[x.name,x.value??x.secretRef]));
assert.equal(appEnv.EVE_AZURE_NETWORK_PROFILE,'private');assert.equal(appEnv.EVE_STORAGE_PROFILE,'azure-private-files-postgres');assert.equal(appEnv.EVE_RELEASE_VERSION,'63.0.0');
assert.equal(priv.outputs.networkProfile.value,'private');assert(priv.outputs.accessRequirement.value.includes('no public Eve endpoint'));
assert(privateDocs.includes('internal-only'));assert(privateDocs.includes('VPN'));assert(privateDocs.includes('ExpressRoute'));
assert(canonical.includes('canonical repository'));assert(canonical.includes('GHCR package settings'));assert(canonical.includes('GitHub Actions'));assert(canonical.includes('Stable'));
assert(setter.includes('OWNER/REPOSITORY'));assert(setter.includes("readFileSync(path.join(root,'VERSION')"));assert(pages.includes('actions/deploy-pages@v4'));assert(pages.includes('stage-deployment-site.sh'));assert(pages.includes('path: _site'));
console.log('v62.2 private Azure + canonical public Eve tests passed');
