'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=(...p)=>fs.readFileSync(path.join(root,...p),'utf8');
const pkg=JSON.parse(read('package.json')),launcher=read('index.html'),config=read('deployment-config.js'),js=read('deployment.js'),pages=read('.github','workflows','publish-beta.yml'),server=read('server.js'),docker=read('Dockerfile');
assert(/^6[23]\./.test(pkg.version));
assert(launcher.includes('Where should Eve run?'));
assert(launcher.includes('deployment.css'));assert(launcher.includes('deployment-config.js'));assert(launcher.includes('deployment.js'));
assert(!fs.existsSync(path.join(root,'factory')),'legacy /factory directory should not remain');
for(const f of ['index.html','app.js','styles.css','sw.js','eve-deployment.js','cloud-storage.js']) assert(fs.existsSync(path.join(root,'app',f)),`missing app/${f}`);
assert(read('app','index.html').includes('<script src="app.js"></script>'));
assert(server.includes("const STATIC_ROOT=path.join(REPO_ROOT,'app');"));
assert(js.includes('https://console.cloud.google.com/cloudshell?show=terminal'));assert(js.includes('googleBootstrapCommand'));assert(config.includes('ghcr.io/OWNER/REPOSITORY:beta'));
assert(pages.includes('stage-deployment-site.sh'));assert(pages.includes('path: _site'));assert(!pages.includes('path: factory'));
assert(docker.includes('CMD ["node","server.js"]'));
console.log('v62.3 canonical root launcher layout tests passed');
